---
- name: Download DB Gate installer
  get_url:
    url: "https://github.com/dbgate/dbgate/releases/latest/download/dbgate-latest.deb"
    dest: "{{ home }}/Downloads/dbgate-latest.deb"
    mode: 0644

- name: Install DB Gate
  apt:
    deb: "{{ home }}/Downloads/dbgate-latest.deb"
    state: present
