- name: Set variables
  set_fact:
    download_url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
    download_destination: "{{ home }}/Downloads/google-chrome-stable_current_amd64.deb"

- name: Download installer
  become: false
  get_url:
    url: "{{ download_url }}"
    dest: "{{ download_destination }}"
    mode: '0755'

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install library to visualize icon
  apt:
    name: 
      - libindicator7
      - libxss1
    state: present
    update_cache: yes

- name: Install Google Chrome
  command: "dpkg -i google-chrome-stable_current_amd64.deb"
  args:
    chdir: "{{ home }}/Downloads"
