---
- name: Add fish repository
  apt_repository:
    repo: ppa:fish-shell/release-3
    state: present
    update_cache: yes

- name: Install fish shell
  apt:
    name: fish
    state: present
    update_cache: yes

- name: Set fish as default shell
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /usr/bin/fish